server:
  port: 2060

spring:
  application:
    name: example2060
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      max-lifetime: 600000
      connection-test-query: SELECT 1
      validation-timeout: 10000


eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost:2072}/eureka/ # http://localhost:2072/eureka/ #Eureka??

