server:
  port: 2073

spring:
  application:
    name: api-gateway
  servlet:
    multipart:
      max-file-size: 3GB
      max-request-size: 3GB
  cloud:
    loadbalancer:
      ribbon:
        enabled: true
      service-discovery:
        timeout: 30000ms

eureka:
  instance:
    instance-id: ${spring.application.name}
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:2072/eureka/ #Eureka??
zuul:
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
  routes:
    example2060:
      path: /example2060/**
      service-id: example2060
      # url: http://localhost:2060
    auth-service:
      path: /auth-service/**
      service-id: auth-service
      # url: http://localhost:2074
    dwg-handler:
      path: /dwg-handler/**
      service-id: dwg-handler
      # url: http://localhost:2075
    file-manage:
      path: /file-manage/**
      service-id: file-manage
      # url: http://localhost:2076
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000
ribbon:
  eureka:
    enabled: true
  restclient:
    enabled: true
    connect-keep-alive: true
    keep-alive-duration: 60000
  ConnectTimeout: 5000       # 连接超时时间
  ReadTimeout: 60000         # 请求处理超时时间
  MaxAutoRetries: 2          # 最大重试次数
  MaxAutoRetriesNextServer: 1  # 切换服务实例后的最大重试次数
  OkToRetryOnAllOperations: true # 允许所有操作重试
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.AvailabilityFilteringRule # 优化服务实例选择
  NFLoadBalancerPingClassName: com.netflix.loadbalancer.DummyPing # 确保服务实例健康检查